config/urls.py
from django.contrib import admin
from django.urls import path, include

from notes.views import redirect_to_note_detail
from user.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_page.urls", namespace="home_page")),
    path('<int:note_id>/', redirect_to_note_detail),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
    path('user/', include("user.urls", namespace="user")),
    path('user/', redirect_to_login),
]

notes/urls.py
"""Notes URL Configuration."""
from django.urls import path
from .views import SectionsView, BySectionView, NoteDetails, SearchResultsView, AddNote

from notes.views import home, search_view, ok_page, edit_note, vote

app_name = "notes"
urlpatterns = [
    path('', home, name="home"),
    path('sections/', SectionsView.as_view(), name="sections"),
    path('sections/<section_name>/', BySectionView.as_view(), name="by_section"),
    path('<int:note_id>/', NoteDetails.as_view(), name="details"),
    path('<int:id>/edit/', edit_note, name="edit_note"),
    path('search/', search_view, name="search_view"),
    path('add/', AddNote.as_view(), name="add_note"),
    path('add/ok', ok_page, name="ok_page"),
    path('<int:id>/vote/', vote, name="vote"),
    path('<str:search_term>/', SearchResultsView.as_view(), name="search"),
]

todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import details

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', details, name="details"),
]

notes/models.py
"""Data for the notes views"""
from config.store import CustomStore


class NoteStore(CustomStore):
    """Store for the notes."""

    model_name = "notes"
    backup = [
        {
            "text": "Web frameworks are a way to improve our productivity and make complex things look easy.",
            "section": "Web Frameworks",
            "voted": 0
        },
        {
            "text": "Django is a web framework written with Python that offers a 'batteries included' approach, as opposed to Flask, that aims at minimizing the initial features to reduce the footprint.",
            "section": "Web Frameworks",
            "voted": 0
        },
        {
            "text": "Most web frameworks use the MVC design pattern that states that logic, data and visualization should be kept in different places.",
            "section": "Web Frameworks",
            "voted": 0
        },
        {
            "text": "Setting up Django is very simple. It requires installing Django, starting a project and an app.",
            "section": "Setting up Django",
            "voted": 0
        },
        {
            "text": "The startproject command lets us specify the directory where the project will be created.",
            "section": "Setting up Django",
            "voted": 0
        },
        {
            "text": "Django comes with a development web server that makes it very simple to install and start working.",
            "section": "Setting up Django",
            "voted": 0
        },
        {
            "text": "URL Mapping can be very easy at the beginning but it may become extremely complex in some cases.",
            "section": "URL Mapping",
            "voted": 0
        },
        {
            "text": "URL endpoints may be defined with literals and parameters, which will be passed on to the view.",
            "section": "URL Mapping",
            "voted": 0
        },
        {
            "text": "Parameters passed with the <b><</b> and <b>></b> will be passed as keyword arguments.",
            "section": "URL Mapping",
            "voted": 0
        },
    ]

notes/forms.py
from django import forms


class SearchForm(forms.Form):
    search_term = forms.CharField(label='Search Term', max_length=200)
    section = forms.ChoiceField(label='Section', required=False, choices=[
        ('', 'All Sections'), 
        ('Web Frameworks', 'Web Frameworks'),
        ('Setting up Django', 'Setting up Django'), 
        ('URL Mapping', 'URL Mapping')
    ])


class NoteForm(forms.Form):
    section = forms.ChoiceField(label='Section', required=False, choices=[
        ('', 'Any'), 
        ('Web Frameworks', 'Web Frameworks'),
        ('Setting up Django', 'Setting up Django'), 
        ('URL Mapping', 'URL Mapping')
    ])
    text  = forms.CharField(widget=forms.Textarea)


class EditNoteForm(forms.Form):
    section = forms.ChoiceField(label='Section', required=False, choices=[
        ('', 'Any'), 
        ('Web Frameworks', 'Web Frameworks'),
        ('Setting up Django', 'Setting up Django'), 
        ('URL Mapping', 'URL Mapping')
        ], disabled=True)
    text  = forms.CharField(widget=forms.Textarea)

notes/views.py
"""Views for the notes app."""
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect, render
from django.template.loader import get_template
from django.views import View
from django.views.generic import TemplateView
from .forms import SearchForm, NoteForm, EditNoteForm

from notes.models import NoteStore
from user.models import UserProfile


store = NoteStore()
notes = store.get()

def redirect_to_note_detail(request, note_id):
    """Redirect to the note details view."""
    return redirect(reverse("notes:details", args=[note_id]))


def home(request):
    """Home for my notes app."""
    template = get_template('notes/notes_page.html')
    context = {
        'sections_url': reverse('notes:sections'),
        'first_note_url': reverse('notes:details', args=[1]),
        'add_note_url': reverse('notes:add_note'),
    }
    rendered_template = template.render(context, request)
    return HttpResponse(rendered_template)


class SectionsView(View):

    def get(self, request):
        """Show the list of note sections."""
        template = get_template('notes/sections.html')
        context = {
            'web_framework': reverse("notes:by_section", args=["Web Frameworks"]),
            'set_up_dj': reverse("notes:by_section", args=["Setting up Django"]),
            'url_map': reverse("notes:by_section", args=["URL Mapping"]),
            'back_home': reverse("notes:home")
        }
        rendered_template = template.render(context, request)
        return HttpResponse(rendered_template)


class BySectionView(View):

    def get(self, request, section_name):
        """Show the notes of a section."""
        template = get_template('notes/by_section.html')
        notes_for_section = self._get_note_items_by_section(section_name)
        context = {
            'section_name': section_name,
            'notes': notes_for_section,
            'back_sections': reverse("notes:sections"),
        }
        rendered_template = template.render(context, request)
        return HttpResponse(rendered_template)


    def _get_note_items_by_section(self, section_name):
        """Return the notes of a section as list items."""
        store = NoteStore()
        notes = store.get()
        return [f"{note['text']}" for note in notes
                if note["section"] == section_name]


class NoteDetails(TemplateView):
    """Note details."""

    template_name = "notes/details.html"

    def get_context_data(self, note_id):
        """Return the note data."""
        store = NoteStore()
        notes = store.get()
        if self.request.user.is_authenticated:
            current_user = self.request.user
            user_profile = UserProfile.objects.get(user=current_user)
        else:
            user_profile = None
        return {
            "id": note_id,
            "num_notes": len(notes),
            "note": notes[note_id - 1],
            'next_note': note_id + 1 if note_id < len(notes) else None,
            'previous_note': note_id - 1 if note_id > 1 else None,
            'user_profile': user_profile,
        }


class SearchResultsView(TemplateView):
    """Execute the search and show results."""

    template_name = "notes/search.html"

    def get_context_data(self, search_term):
        """Return the term and list of notes."""
        result = [(note['section'], note['text']) for note in notes if search_term.lower() in note['text'].lower()]
        return {
            "term": search_term,
            "result": result,
        }


def search_view(request):
    form = SearchForm()
    store = NoteStore()
    notes = store.get()
    result = []

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search_term = form.cleaned_data['search_term']
            section = form.cleaned_data['section']
            
            for note in notes:
                if section == 'All Categories' or not section: 
                    if search_term.lower() in note['text'].lower():
                        result.append((note['section'], note['text']))
                elif section:
                    if note['section'] == section:
                        if search_term.lower() in note['text'].lower():
                            result.append((note['section'], note['text']))
            
            return render(request, "notes/search.html", {"form": form, "term": search_term, "section": section, 'result': result})
        
    elif request.method == "GET":
        form = SearchForm()
        # search_term = request.GET.get('search_term', None)
        # section = request.GET.get('section', None)

    return render(request, "notes/search.html", {"form": form})


def ok_page(request):
    return render(request, "notes/ok.html")


class AddNote(View):

    def post(self, request):
        form = NoteForm(request.POST)
        if form.is_valid():
            section = form.cleaned_data['section']
            text = form.cleaned_data['text']
            store = NoteStore()
            notes = store.get()
            notes.append({'section': section, 'text': text})
            store.save(notes)
            return redirect('notes:ok_page')
        
    def get(self, request):
        form = NoteForm()
        return render(request, 'notes/add_note.html', {"form": form})


def edit_note(request, id):
    store = NoteStore()
    notes = store.get()
    note = notes[id - 1]
    
    if request.method == 'GET':
        form = EditNoteForm(initial={'text':note['text']})
        return render(request, 'notes/edit_note.html', {'form': form})
    
    elif request.method == 'POST':
        form = EditNoteForm(request.POST)
        if form.is_valid():
            note['text'] = form.cleaned_data['text']
            store.save(notes)
            return redirect('notes:details', id)


def vote(request, id):

    if request.method == "GET":
        store = NoteStore()
        notes = store.get()
        notes[id - 1]["voted"] += 1
        store.save(notes)

        current_user = request.user
        user_profile = UserProfile.objects.get(user=current_user) 
        user_profile.voted = True
        user_profile.save()

        context = {
        "id": id,
        "num_notes": len(notes),
        "note": notes[id - 1],
        'next_note': id + 1 if id < len(notes) else None,
        'previous_note': id - 1 if id > 1 else None,
        'user_profile': user_profile
        }
        return render(request, 'notes/details.html', context)

templates/notes/add_note.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Add Note</h2>

{% if user.is_superuser %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="Submit" value="Add">
</form>

{% else %}

<p>You are not authorized to access this content. <a href="/user">Log in</a> to gain access.</p>

{% endif %}

{% endblock %}

templates/notes/by_section.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Notes about {{section_name}}</h2>
<ul>
    {% for note in notes %} 
        <li>{{ note }}</li>
    {% endfor %}
</ul>
<a href="{{ back_sections }}">Back to sections</a>

{% endblock %}

templates/notes/details.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Note number {{ id }}</h2>
<h3><b>Section: </b>{{ note.section }}</h3>
{% if user_profile %}
    {% if user_profile.voted %}
    <p><b>Votes:</b> {{ note.voted }}. You are already voted</p>
    {% elif not user_profile.voted %}
    <p><b>Votes:</b> {{ note.voted }} <a href="{% url 'notes:vote' id %}">Vote</a></p>
    {% endif %}
{% else %}
<p><b>Votes:</b> {{ note.voted }} You are not allowed to vote. <a href="/user/">Log in</a> to gain access</p>
<p>{{ note.text }}</p>
{% endif %}

<a href="{% url 'notes:edit_note' id %}">Edit this note</a>

<br>
<br>

{% if previous_note %}
    <a href="{% url 'notes:details' previous_note %}">Previous note</a>
{% else %}
    <span style="color: rgb(0, 0, 0);">Previous note</span>
{% endif %}

{% if next_note %}
    <a href="{% url 'notes:details' next_note %}">Next note</a>
{% else %}
    <span style="color: rgb(0, 0, 0);">Next note</span>
{% endif %}

{% endblock %}

templates/notes/edit_note.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Edit Note</h2>

{% if user.is_superuser %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="Submit" value="Save Changes">
</form>

{% else %}

<p>You are not authorized to access this content. <a href="/user">Log in</a> to gain access.</p>

{% endif %}

{% endblock %}

templates/notes/notes_page.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Welcome to my course notes!</h2>
<ul>
    <li><a href="{% url 'notes:sections' %}">Check the list of sections</a></li>
    <li><a href="{% url 'notes:details' 1 %}">Read my first note</a></li>
    <li><a href="{% url 'notes:search_view'%}">Search note</a></li>
    <li><a href="{% url 'notes:add_note'%}">Add note</a></li>
</ul>
{% endblock %}

templates/notes/ok.html
{% extends 'base_notes.html' %}


{% block content %}

<p>The note was added successfully</p>

<p>Add <a href="{% url 'notes:add_note'%}">another note</a>.</p>

{% endblock %}

templates/notes/search.html
{% extends 'base_notes.html' %}
{% load my_tags %}


{% block content %}

<h2>Notes matching {{ term }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

<ul>
    {% if term %} 
        {% if section %} 
        <p>Notes matching {{ term }} in section {{ section }} </p>
        {% elif not section %}
        <p>Notes matching {{ term }}</p>
        {% endif %}
    {% endif %}

    {% for section, text in result %}
        <li>{{ text }}</li>
        <em>Filed under section</em> {{ section|linkable_section|safe }}
    {% endfor %}
</ul>

{% endblock %}

templates/notes/sections.html
{% extends 'base_notes.html' %}


{% block content %}

<h2>Browse my notes by section</h2>
<ol>
    <li><a href="{% url 'notes:by_section' 'Web Frameworks' %}">Web Frameworks</a></li>
    <li><a href="{% url 'notes:by_section' 'Setting up Django' %}">Setting up Django</a></li>
    <li><a href="{% url 'notes:by_section' 'URL Mapping' %}">URL Mapping</a></li>
</ol>


<a href="{% url 'notes:home' %}">Back to home</a>

{% endblock %}