config/urls.py
from django.contrib import admin
from django.urls import path, include

from notes.views import redirect_to_note_detail
from user.views import redirect_to_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_page.urls", namespace="home_page")),
    path('<int:note_id>/', redirect_to_note_detail),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
    path('user/', include("user.urls", namespace="user")),
    path('user/', redirect_to_login),
]

todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import details

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', details, name="details"),
]

todo/models.py
from django.db import models


# class User(models.Model):
#     login = models.CharField(max_length=20)
#     password = models.CharField(max_length=20)


# credentials = [
#     {
#         "login": "mks_kh",
#         "password": "test1234"
#     },
# ]


todos = [
    {
        "text": "Start the repository",
        "topic": "Course Project",
        "status": "done"
    },
    {
        "text": "Set up Django",
        "topic": "Course Project",
        "status": "done"
    },
    {
        "text": "Read more about URLconf",
        "topic": "Lectures",
        "status": "done"
    },
    {
        "text": "Fix the cabinet",
        "topic": "Personal",
        "status": "done"
    },
    {
        "text": "Create forms",
        "topic": "Course Project",
        "status": "pending"
    },
]


# class ToDoList(models.Model):
#     title = models.CharField(max_length=100)
#     text = models.TextField()
#     status = models.BooleanField(default=False)

todo/forms.py
from django import forms

todo/views.py
"""Todo views."""
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect, render

from todo.models import todos

def details(request, todo_id):
        """Show a single todo matching the todo_id."""
        todo = todos[todo_id - 1]
        previous = todo_id - 1 if todo_id > 1 else None
        next = todo_id + 1 if todo_id < len(todos) else None

        response = {
                "todo": todo,
                "previous": previous,
                "next": next,
                }

        return render(request, "todo/details.html", response)

templates/todo/details.html
{% extends 'base.html' %}


{% block content %}

{% if user.is_authenticated %}

<h2>To Do number {{ id }}</h2>
<h3>{{ todo.topic }}</h3>
<p>{{ todo.text }}</p>
<p>{{ todo.status }}</p>
{% if previous %}
    <a href="{% url 'todo:details' previous %}">Previous note</a>
{% else %}
    <span style="color: rgb(0, 0, 0);">Previous note</span>
{% endif %}

{% if next%}
    <a href="{% url 'todo:details' next %}">Next note</a>
{% else %}
    <span style="color: rgb(0, 0, 0);">Next note</span>
{% endif %}

{% else %}

<p><a href="/user/login">Log in</a> to view notes. </p>

{% endif %}

{% endblock %}